name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ○ Install Node + your favourite package manager
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci        # or pnpm install / yarn install
      - run: npm run build # creates ./dist

      # ○ Push the dist folder into the same branch (works for user sites)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main          # because user sites read from / (root)
          publish_dir: ./dist
          keep_files: true              # keep source files alongside the build
